version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "10:00"
    open-pull-requests-limit: 10
    reviewers:
      - jiujiteiro
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      time: "10:00"
    open-pull-requests-limit: 10
    reviewers:
      - jiujiteiro
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    reviewers:
      - jiujiteiro
    labels:
      - dependencies