accounts:
  - name: eduardo
    coins: ["2000000000000000000000000ario", "2000000000000000000000000arst"]
  - name: aaron
    coins: ["2000000000000000000000000ario", "2000000000000000000000000arst"]
validator:
  name: eduardo
  staked: "100000000000000000000000ario"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: aaron
  coins: ["1000000000000000000000ario"]
genesis:
  chain_id: "realio-local-1"
  app_state:
    staking:
      params:
        bond_denom: "ario,arst"
        historical_entries: "10"
        max_validators: "10"
        unbonding_time: "300000000000ns"
    mint:
      params:
        mint_denom: "ario"
    crisis:
      constant_fee:
        denom: "ario"
    evm:
      params:
        evm_denom: "ario"
build:
  binary: "realio-networkd"
init:
  home: "$HOME/.realio-network"
  app:
    evm-rpc:
      address: "0.0.0.0:8545"     # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546"  # change the JSON-RPC websocket address and port

